/**
 * Report generation service — creates scheduled and on-demand reports.
 * Uses DB-level aggregations instead of loading all records into memory.
 *
 * Supports two modes:
 *   - Synchronous: generateReport() — computes report inline (for small datasets)
 *   - Asynchronous: enqueueReport() — creates a pending report and returns immediately,
 *     report is generated by a background worker (for large datasets / email delivery)
 */

import { prisma } from "../lib/prisma";
import { sendEmail } from "./notification.service";
import { dateOnlyStringFrom, dateTimeFrom, moneyFrom, moneyToNumber } from "../utils/safe-fields";
import { assertSchoolScope } from "../lib/tenant-scope";

export type ReportType =
  | "attendance_weekly"
  | "attendance_monthly"
  | "fee_summary"
  | "student_performance"
  | "class_analytics";

export interface ReportConfig {
  schoolId: string;
  type: ReportType;
  startDate: string;
  endDate: string;
  filters?: Record<string, string>;
  recipientEmails?: string[];
  requestedBy: string;
}

export interface ReportResult {
  id: string;
  type: ReportType;
  html: string;
  stats: Record<string, unknown>;
  generatedAt: string;
  deliveredTo: string[];
}

export async function generateReport(config: ReportConfig): Promise<ReportResult> {
  const { schoolId, type, startDate, endDate, filters } = config;
  assertSchoolScope(schoolId);

  const startDateDt = dateTimeFrom(startDate);
  const endDateDt = dateTimeFrom(endDate);

  if (!startDateDt || !endDateDt) {
    throw new Error("Invalid startDate or endDate");
  }

  let html: string;
  let stats: Record<string, unknown>;

  switch (type) {
    case "attendance_weekly":
    case "attendance_monthly":
      ({ html, stats } = await generateAttendanceReport(schoolId, startDate, endDate, filters));
      break;
    case "fee_summary":
      ({ html, stats } = await generateFeeReport(schoolId, startDate, endDate, filters));
      break;
    case "student_performance":
      ({ html, stats } = await generatePerformanceReport(schoolId, startDate, endDate, filters));
      break;
    case "class_analytics":
      ({ html, stats } = await generateClassAnalytics(schoolId, startDate, endDate, filters));
      break;
    default:
      throw new Error(`Unknown report type: ${type}`);
  }

  // Persist report record
  const report = await prisma.report.create({
    data: {
      schoolId,
      type,
      startDate: startDateDt,
      endDate: endDateDt,
      filters: filters ? (filters as any) : undefined,
      stats: stats ? (stats as any) : undefined,
      html,
      status: "completed",
      requestedBy: config.requestedBy,
      deliveredTo: [],
      generatedAt: new Date(),
    },
  });

  const result: ReportResult = {
    id: report.id,
    type,
    html,
    stats,
    generatedAt: report.generatedAt.toISOString(),
    deliveredTo: [],
  };

  // Send via email if recipients provided
  if (config.recipientEmails && config.recipientEmails.length > 0) {
    const school = await prisma.school.findUnique({ where: { id: schoolId } });
    const schoolName = school?.name ?? "SuffaCampus School";
    const reportTitle = getReportTitle(type);

    for (const email of config.recipientEmails) {
      const sent = await sendEmail({
        to: email,
        subject: `${reportTitle} — ${schoolName} (${startDate} to ${endDate})`,
        html: wrapInEmailTemplate(html, schoolName, reportTitle),
      });
      if (sent) result.deliveredTo.push(email);
    }

    await prisma.report.update({
      where: { id: report.id },
      data: { deliveredTo: result.deliveredTo },
    });
  }

  return result;
}

/**
 * Enqueue a report for background generation.
 * Returns immediately with a pending report ID.
 * The worker calls executeReportById() to generate it.
 */
export async function enqueueReport(config: ReportConfig): Promise<{ id: string; status: string }> {
  const { schoolId, type, startDate, endDate, filters } = config;
  assertSchoolScope(schoolId);

  const startDateDt = dateTimeFrom(startDate);
  const endDateDt = dateTimeFrom(endDate);

  if (!startDateDt || !endDateDt) {
    throw new Error("Invalid startDate or endDate");
  }

  const report = await prisma.report.create({
    data: {
      schoolId,
      type,
      startDate: startDateDt,
      endDate: endDateDt,
      filters: filters ? (filters as any) : undefined,
      status: "pending",
      requestedBy: config.requestedBy,
      deliveredTo: config.recipientEmails ?? [],
      generatedAt: new Date(),
    },
  });

  return { id: report.id, status: "pending" };
}

/**
 * Execute a previously enqueued report by ID.
 * Called by the background worker.
 */
export async function executeReportById(reportId: string): Promise<void> {
  const report = await prisma.report.findUnique({ where: { id: reportId } });
  if (!report) throw new Error(`Report not found: ${reportId}`);
  if (report.status === "completed") return;

  await prisma.report.update({
    where: { id: reportId },
    data: { status: "processing" },
  });

  try {
    const config: ReportConfig = {
      schoolId: report.schoolId,
      type: report.type as ReportType,
      startDate: report.startDate.toISOString(),
      endDate: report.endDate.toISOString(),
      filters: (report.filters as Record<string, string>) ?? undefined,
      recipientEmails: report.deliveredTo ?? [],
      requestedBy: report.requestedBy,
    };

    const result = await generateReport(config);

    await prisma.report.update({
      where: { id: reportId },
      data: {
        status: "completed",
        stats: result.stats as any,
        html: result.html,
        deliveredTo: result.deliveredTo,
      },
    });
  } catch (err: any) {
    await prisma.report.update({
      where: { id: reportId },
      data: {
        status: "failed",
        error: err.message ?? String(err),
      },
    });
    throw err;
  }
}

/**
 * Get a report by ID — used by clients polling for async report completion.
 */
export async function getReportById(reportId: string, schoolId: string) {
  assertSchoolScope(schoolId);

  const report = await prisma.report.findFirst({
    where: { id: reportId, schoolId },
  });

  if (!report) return null;
  return report;
}

// ---------------------------------------------------------------------------
// Individual report generators — all use DB-level aggregations
// ---------------------------------------------------------------------------

async function generateAttendanceReport(
  schoolId: string,
  startDate: string,
  endDate: string,
  filters?: Record<string, string>
): Promise<{ html: string; stats: Record<string, unknown> }> {
  assertSchoolScope(schoolId);

  const startDateDt = dateTimeFrom(startDate);
  const endDateDt = dateTimeFrom(endDate);

  if (!startDateDt || !endDateDt) {
    throw new Error("Invalid attendance report date range");
  }

  const endOfDay = new Date(endDateDt);
  endOfDay.setHours(23, 59, 59, 999);

  const where: any = { schoolId, date: { gte: startDateDt, lte: endOfDay } };
  if (filters?.classId) where.classId = filters.classId;

  // Use groupBy instead of loading all records
  const [statusCounts, dailyGroups] = await Promise.all([
    prisma.attendance.groupBy({
      by: ["status"],
      where,
      _count: true,
    }),
    prisma.attendance.groupBy({
      by: ["date", "status"],
      where,
      _count: true,
    }),
  ]);

  // Compute totals from status group counts
  let totalRecords = 0;
  let presentCount = 0;
  let absentCount = 0;
  let lateCount = 0;

  for (const group of statusCounts) {
    totalRecords += group._count;
    if (group.status === "Present") presentCount = group._count;
    else if (group.status === "Absent") absentCount = group._count;
    else if (group.status === "Late") lateCount = group._count;
  }

  const attendanceRate = totalRecords > 0 ? ((presentCount / totalRecords) * 100).toFixed(1) : "0";

  // Build daily breakdown from groupBy results
  const byDate = new Map<string, { present: number; absent: number; late: number; total: number }>();
  for (const group of dailyGroups) {
    const dateKey = dateOnlyStringFrom(group.date);
    if (!byDate.has(dateKey)) byDate.set(dateKey, { present: 0, absent: 0, late: 0, total: 0 });
    const d = byDate.get(dateKey)!;
    d.total += group._count;
    if (group.status === "Present") d.present += group._count;
    else if (group.status === "Absent") d.absent += group._count;
    else if (group.status === "Late") d.late += group._count;
  }

  const dateRows = Array.from(byDate.entries())
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([date, d]) =>
      `<tr><td>${date}</td><td>${d.present}</td><td>${d.absent}</td><td>${d.late}</td><td>${d.total}</td><td>${((d.present / d.total) * 100).toFixed(1)}%</td></tr>`
    )
    .join("");

  const stats = { totalRecords, presentCount, absentCount, lateCount, attendanceRate: `${attendanceRate}%` };

  const html = `
    <div class="report-stats">
      <div class="stat-card"><div class="stat-label">Total Records</div><div class="stat-value">${totalRecords}</div></div>
      <div class="stat-card"><div class="stat-label">Present</div><div class="stat-value" style="color:#16a34a">${presentCount}</div></div>
      <div class="stat-card"><div class="stat-label">Absent</div><div class="stat-value" style="color:#dc2626">${absentCount}</div></div>
      <div class="stat-card"><div class="stat-label">Late</div><div class="stat-value" style="color:#f59e0b">${lateCount}</div></div>
      <div class="stat-card"><div class="stat-label">Rate</div><div class="stat-value" style="color:#2563eb">${attendanceRate}%</div></div>
    </div>
    <table class="report-table">
      <thead><tr><th>Date</th><th>Present</th><th>Absent</th><th>Late</th><th>Total</th><th>Rate</th></tr></thead>
      <tbody>${dateRows}</tbody>
    </table>
  `;

  return { html, stats };
}

async function generateFeeReport(
  schoolId: string, startDate: string, endDate: string, _filters?: Record<string, string>
): Promise<{ html: string; stats: Record<string, unknown> }> {
  assertSchoolScope(schoolId);

  // Build date-scoped where clause (now actually uses date params)
  const where: any = { schoolId };
  const startDateDt = dateTimeFrom(startDate);
  const endDateDt = dateTimeFrom(endDate);
  if (startDateDt && endDateDt) {
    where.createdAt = { gte: startDateDt, lte: endDateDt };
  }

  // Use groupBy/aggregate instead of loading all records
  const [statusGroups, totals] = await Promise.all([
    prisma.fee.groupBy({
      by: ["status"],
      where,
      _count: true,
      _sum: { amount: true, amountPaid: true },
    }),
    prisma.fee.aggregate({
      where,
      _sum: { amount: true },
      _count: true,
    }),
  ]);

  const totalFees = totals._count;
  const totalAmount = moneyToNumber(moneyFrom(totals._sum.amount));

  let collectedAmountMoney = moneyFrom(null, 0);
  let pendingAmountMoney = moneyFrom(null, 0);
  let paidCount = 0;
  let pendingCount = 0;
  let overdueCount = 0;

  for (const group of statusGroups) {
    const sumMoney = moneyFrom(group._sum.amount);
    const paidMoney = moneyFrom(group._sum.amountPaid);

    if (group.status === "Paid") {
      paidCount = group._count;
      collectedAmountMoney = collectedAmountMoney.plus(sumMoney);
    } else if (group.status === "Partial") {
      collectedAmountMoney = collectedAmountMoney.plus(paidMoney);
    }

    if (group.status === "Pending") {
      pendingCount = group._count;
      pendingAmountMoney = pendingAmountMoney.plus(sumMoney);
    }

    if (group.status === "Overdue") {
      overdueCount = group._count;
      pendingAmountMoney = pendingAmountMoney.plus(sumMoney);
    }
  }

  const collectedAmount = moneyToNumber(collectedAmountMoney);
  const pendingAmount = moneyToNumber(pendingAmountMoney);
  const collectionRate = totalAmount > 0 ? ((collectedAmount / totalAmount) * 100).toFixed(1) : "0";

  const stats = {
    totalFees,
    totalAmount,
    collectedAmount,
    pendingAmount,
    collectionRate: `${collectionRate}%`,
    paidCount,
    pendingCount,
    overdueCount,
  };

  const html = `
    <div class="report-stats">
      <div class="stat-card"><div class="stat-label">Total Fees</div><div class="stat-value">${totalFees}</div></div>
      <div class="stat-card"><div class="stat-label">Total Amount</div><div class="stat-value">₹${totalAmount.toLocaleString("en-IN")}</div></div>
      <div class="stat-card"><div class="stat-label">Collected</div><div class="stat-value" style="color:#16a34a">₹${collectedAmount.toLocaleString("en-IN")}</div></div>
      <div class="stat-card"><div class="stat-label">Pending</div><div class="stat-value" style="color:#f59e0b">₹${pendingAmount.toLocaleString("en-IN")}</div></div>
      <div class="stat-card"><div class="stat-label">Rate</div><div class="stat-value" style="color:#2563eb">${collectionRate}%</div></div>
    </div>
  `;

  return { html, stats };
}

async function generatePerformanceReport(
  schoolId: string, _startDate: string, _endDate: string, filters?: Record<string, string>
): Promise<{ html: string; stats: Record<string, unknown> }> {
  assertSchoolScope(schoolId);

  const where: any = { schoolId, isActive: true };
  if (filters?.classId) where.classId = filters.classId;
  if (filters?.examType) where.examType = filters.examType;

  // Use aggregate + raw query for grade buckets instead of loading all records
  const [totals, totalRecordCount] = await Promise.all([
    prisma.result.aggregate({
      where,
      _sum: { marksObtained: true, totalMarks: true },
      _count: true,
    }),
    prisma.result.count({ where }),
  ]);

  const totalResults = totals._count;
  const totalMarks = Number(totals._sum.marksObtained ?? 0);
  const totalMaxMarks = Number(totals._sum.totalMarks ?? 0);
  const avgPercentage = totalMaxMarks > 0 ? ((totalMarks / totalMaxMarks) * 100).toFixed(1) : "0";

  // For grade distribution, use raw SQL to avoid loading all records
  // Prisma doesn't support computed groupBy, so we use a bounded query with select
  // For safety, limit to reasonable batch for grade calculation
  let grades = { A: 0, B: 0, C: 0, D: 0, F: 0 };

  try {
    const gradeRows = await prisma.$queryRawUnsafe<Array<{ grade: string; count: bigint }>>(
      `SELECT 
        CASE
          WHEN ("marksObtained"::float / NULLIF("totalMarks"::float, 0)) * 100 >= 90 THEN 'A'
          WHEN ("marksObtained"::float / NULLIF("totalMarks"::float, 0)) * 100 >= 75 THEN 'B'
          WHEN ("marksObtained"::float / NULLIF("totalMarks"::float, 0)) * 100 >= 60 THEN 'C'
          WHEN ("marksObtained"::float / NULLIF("totalMarks"::float, 0)) * 100 >= 40 THEN 'D'
          ELSE 'F'
        END AS grade,
        COUNT(*) AS count
      FROM "Result"
      WHERE "schoolId" = $1 AND "isActive" = true
      ${filters?.classId ? `AND "classId" = $2` : ""}
      ${filters?.examType ? `AND "examType" = ${filters?.classId ? "$3" : "$2"}` : ""}
      GROUP BY grade`,
      schoolId,
      ...(filters?.classId ? [filters.classId] : []),
      ...(filters?.examType ? [filters.examType] : [])
    );

    for (const row of gradeRows) {
      const key = row.grade as keyof typeof grades;
      if (key in grades) {
        grades[key] = Number(row.count);
      }
    }
  } catch {
    // Fallback: if raw SQL fails, use bounded findMany
    const records = await prisma.result.findMany({
      where,
      select: { marksObtained: true, totalMarks: true },
      take: 5000,
    });
    for (const r of records) {
      const pct = (Number(r.marksObtained) / (Number(r.totalMarks) || 1)) * 100;
      if (pct >= 90) grades.A++;
      else if (pct >= 75) grades.B++;
      else if (pct >= 60) grades.C++;
      else if (pct >= 40) grades.D++;
      else grades.F++;
    }
  }

  const stats = { totalResults, avgPercentage: `${avgPercentage}%`, grades };
  const html = `
    <div class="report-stats">
      <div class="stat-card"><div class="stat-label">Total Results</div><div class="stat-value">${totalResults}</div></div>
      <div class="stat-card"><div class="stat-label">Avg %</div><div class="stat-value" style="color:#2563eb">${avgPercentage}%</div></div>
      <div class="stat-card"><div class="stat-label">Grade A</div><div class="stat-value" style="color:#16a34a">${grades.A}</div></div>
      <div class="stat-card"><div class="stat-label">Grade F</div><div class="stat-value" style="color:#dc2626">${grades.F}</div></div>
    </div>
  `;

  return { html, stats };
}

async function generateClassAnalytics(
  schoolId: string, _startDate: string, _endDate: string, _filters?: Record<string, string>
): Promise<{ html: string; stats: Record<string, unknown> }> {
  assertSchoolScope(schoolId);

  const [classes, studentCounts] = await Promise.all([
    prisma.class.findMany({ where: { schoolId, isActive: true }, include: { sections: true } }) as any,
    prisma.student.groupBy({ by: ["classId"], where: { schoolId, isDeleted: false }, _count: true }) as any,
  ]);

  const countMap: Record<string, number> = Object.fromEntries(studentCounts.map((c: any) => [c.classId, c._count]));
  const totalStudents = studentCounts.reduce((s: number, c: any) => s + c._count, 0);
  const totalClasses = classes.length;
  const avgClassSize = totalClasses > 0 ? Math.round(totalStudents / totalClasses) : 0;

  const classRows = classes.map((c: any) =>
    `<tr><td>${c.className}</td><td>${countMap[c.id] ?? 0}</td><td>${c.sections.length}</td></tr>`
  ).join("");

  const stats = { totalClasses, totalStudents, avgClassSize };
  const html = `
    <div class="report-stats">
      <div class="stat-card"><div class="stat-label">Classes</div><div class="stat-value">${totalClasses}</div></div>
      <div class="stat-card"><div class="stat-label">Students</div><div class="stat-value">${totalStudents}</div></div>
      <div class="stat-card"><div class="stat-label">Avg Size</div><div class="stat-value">${avgClassSize}</div></div>
    </div>
    <table class="report-table">
      <thead><tr><th>Class</th><th>Students</th><th>Sections</th></tr></thead>
      <tbody>${classRows}</tbody>
    </table>
  `;

  return { html, stats };
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function getReportTitle(type: ReportType): string {
  const titles: Record<ReportType, string> = {
    attendance_weekly: "Weekly Attendance Report",
    attendance_monthly: "Monthly Attendance Report",
    fee_summary: "Fee Collection Summary",
    student_performance: "Student Performance Report",
    class_analytics: "Class Analytics Report",
  };
  return titles[type] ?? "Report";
}

function wrapInEmailTemplate(bodyHtml: string, schoolName: string, title: string): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #f8fafc; margin: 0; padding: 24px; color: #1e293b; }
    .container { max-width: 700px; margin: 0 auto; background: white; border-radius: 12px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
    .header { background: linear-gradient(135deg, #2563eb, #1d4ed8); color: white; padding: 24px 32px; }
    .header h1 { margin: 0; font-size: 20px; font-weight: 700; }
    .header p { margin: 4px 0 0; opacity: 0.85; font-size: 13px; }
    .body { padding: 24px 32px; }
    .report-stats { display: flex; gap: 12px; flex-wrap: wrap; margin-bottom: 24px; }
    .stat-card { flex: 1; min-width: 110px; padding: 12px 16px; background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; }
    .stat-label { font-size: 10px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.5px; color: #94a3b8; }
    .stat-value { font-size: 20px; font-weight: 700; color: #0f172a; margin-top: 4px; }
    .report-table { width: 100%; border-collapse: collapse; font-size: 13px; }
    .report-table th { text-align: left; padding: 10px 12px; background: #f1f5f9; font-size: 11px; font-weight: 600; color: #475569; text-transform: uppercase; border-bottom: 2px solid #e2e8f0; }
    .report-table td { padding: 8px 12px; border-bottom: 1px solid #f1f5f9; color: #334155; }
    .footer { padding: 16px 32px; background: #f8fafc; border-top: 1px solid #e2e8f0; text-align: center; font-size: 11px; color: #94a3b8; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>${schoolName}</h1>
      <p>${title} &mdash; Generated ${new Date().toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" })}</p>
    </div>
    <div class="body">${bodyHtml}</div>
    <div class="footer"><p>Generated by SuffaCampus &bull; ${new Date().toISOString()}</p></div>
  </div>
</body>
</html>`;
}
